example_project/example_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('helpcenter.urls')),
]

helpcenter/api/urls.py
from django.conf.urls import include, url

from rest_framework.routers import SimpleRouter

from helpcenter.api import views


router = SimpleRouter()
router.register(r'articles', views.ArticleViewSet)
router.register(r'categories', views.CategoryViewSet)


app_name = 'helpcenter-api'

urlpatterns = [
    url(r'^permissions/$', views.PermissionsView.as_view(),
        name='permissions'),
    url(r'^', include(router.urls)),
]

helpcenter/urls.py
from django.conf.urls import include, url

from helpcenter import views


app_name = 'helpcenter'

urlpatterns = [
    url(r'^api/', include('helpcenter.api.urls', app_name='helpcenter-api',
        namespace='api')),
    url(r'^articles/create/$', views.ArticleCreateView.as_view(),
        name='article-create'),
    url(r'^articles/(?P<pk>[0-9]+)/$', views.ArticleDetailView.as_view(),
        name='article-detail'),
    url(r'^articles/(?P<pk>[0-9]+)/delete/$',
        views.ArticleDeleteView.as_view(), name='article-delete'),
    url(r'^articles/(?P<pk>[0-9]+)/update/$',
        views.ArticleUpdateView.as_view(), name='article-update'),
    url(r'^categories/create/$', views.CategoryCreateView.as_view(),
        name='category-create'),
    url(r'^categories/(?P<pk>[0-9]+)/$', views.CategoryDetailView.as_view(),
        name='category-detail'),
    url(r'^categories/(?P<pk>[0-9]+)/delete/$',
        views.CategoryDeleteView.as_view(), name='category-delete'),
    url(r'^categories/(?P<pk>[0-9]+)/update/$',
        views.CategoryUpdateView.as_view(), name='category-update'),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^$', views.IndexView.as_view(), name='index'),
]

helpcenter/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone


class Article(models.Model):
    """ Model to represent a help article """
    body = models.TextField(
        help_text="The body of an article can contain HTML as well as text.",
        verbose_name="Article Body Content")

    category = models.ForeignKey(
        'Category',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text="The parent category for the article.",
        verbose_name="Article Category")

    draft = models.BooleanField(
        default=False,
        help_text="Marking an article as a draft will hide it from users.",
        verbose_name="article is a draft")

    time_edited = models.DateTimeField(
        auto_now=True,
        verbose_name="time last modifed")

    time_published = models.DateTimeField(
        default=timezone.now,
        help_text=("Please use the following format: ",
                   "<em>YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]</em>"),
        verbose_name="Time Published")

    title = models.CharField(
        max_length=200,
        db_index=True,
        help_text="An article title is restricted to 200 characters.",
        verbose_name="Article Title")

    def __str__(self):
        """ Return the Article's title """
        return self.title

    def get_absolute_url(self):
        """ Get the url of the instance's detail view """
        return reverse('helpcenter:article-detail', kwargs={'pk': self.pk})

    def get_delete_url(self):
        """ Get the url of the instance's delete view """
        return reverse('helpcenter:article-delete', kwargs={'pk': self.pk})

    def get_parent_url(self):
        """ Get the url of the instance's parent """
        if self.category:
            return self.category.get_absolute_url()

        return reverse('helpcenter:index')

    def get_update_url(self):
        """ Get the url of the instance's update view """
        return reverse('helpcenter:article-update', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        """Save the article instance to the database.

        This overrides Django's default save method in order to update
        the instance's `time_published` attribute if the instance is
        being converted from a draft to a normal article.

        Args:
            *args: Passed to the default implementation.
            **kwargs: Passed to the default implementation.

        Returns:
            Article: The new saved instance.
        """
        if self.pk and not self.draft:
            old_obj = Article.objects.get(pk=self.pk)

            if old_obj.draft:
                self.time_published = timezone.now()

        return super(Article, self).save(*args, **kwargs)


class Category(models.Model):
    """ Model to represent a category to contain articles """
    title = models.CharField(
        max_length=200,
        db_index=True,
        help_text="A category's title is restricted to 200 characters.",
        verbose_name="Category Title")

    parent = models.ForeignKey(
        'Category',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text="Categories can be nested as deep as you would like.",
        verbose_name="Parent Category")

    class Meta:
        """ Meta options for the Category model """
        verbose_name_plural = 'categories'

    def __str__(self):
        """ Return the Category's title """
        return self.title

    @property
    def article_list(self):
        """List of articles in this category.

        If the setting `HELPCENTER_EXPANDED_ARTICLE_LIST` is true, this
        list will include all the articles in this instance's child
        categories as well.
        """
        if getattr(settings, 'HELPCENTER_EXPANDED_ARTICLE_LIST', False):
            articles = self.article_set.all()

            for category in self.category_set.all():
                articles |= category.article_list

            return articles

        return self.article_set.all()

    def get_absolute_url(self):
        """ Get the url of the instance's detail view """
        return reverse('helpcenter:category-detail', kwargs={'pk': self.pk})

    def get_delete_url(self):
        """ Get the url of the instance's delete view """
        return reverse('helpcenter:category-delete', kwargs={'pk': self.pk})

    def get_parent_url(self):
        """ Get the url of the instance's parent container """
        if self.parent:
            return self.parent.get_absolute_url()

        return reverse('helpcenter:index')

    def get_update_url(self):
        """ Get the url of the instance's update view """
        return reverse('helpcenter:category-update', kwargs={'pk': self.pk})

    @property
    def num_articles(self):
        """int: Return the number of articles in the category."""
        articles = self.article_set.exclude(draft=True).count()

        for category in self.category_set.all():
            articles += category.num_articles

        return articles

helpcenter/api/views.py
from rest_framework import permissions, viewsets
from rest_framework.response import Response
from rest_framework.views import APIView

from helpcenter import models
from helpcenter.api import serializers


class ArticleViewSet(viewsets.ModelViewSet):
    """ View set for the Article model """
    permission_classes = (
        permissions.DjangoModelPermissionsOrAnonReadOnly,
    )
    queryset = models.Article.objects.all()
    serializer_class = serializers.ArticleSerializer


class CategoryViewSet(viewsets.ModelViewSet):
    """ View set for the Category model """
    permission_classes = (
        permissions.DjangoModelPermissionsOrAnonReadOnly,
    )
    queryset = models.Category.objects.all()
    serializer_class = serializers.CategorySerializer


class PermissionsView(APIView):
    """ View for user permissions in the help center """
    permission_classes = (permissions.IsAuthenticated,)
    permissions_to_check = [
        'add_article',
        'add_category',
        'change_article',
        'change_category',
        'delete_article',
        'delete_category',
    ]

    def get(self, request, *args, **kwargs):
        """ Handle GET requests """
        r = {}

        for perm in self.permissions_to_check:
            r[perm] = request.user.has_perm(perm)

        return Response(r)

helpcenter/views.py
from django.shortcuts import render
from django.views import generic

from helpcenter import models
from helpcenter.backends.search import SimpleSearch
from helpcenter.mixins import OptionalFormMixin, PermissionsMixin


class ArticleCreateView(OptionalFormMixin, PermissionsMixin,
                        generic.edit.CreateView):
    """View for creating new Article instances."""
    fields = ('title', 'body', 'category', 'draft')
    form_class_setting = 'HELPCENTER_ARTICLE_CREATE_FORM'
    model = models.Article
    permissions = ('helpcenter.add_article',)
    template_name_suffix = '_create'


class ArticleDeleteView(PermissionsMixin, generic.edit.DeleteView):
    """ View for deleting an Article instance """
    model = models.Article
    permissions = ('helpcenter.delete_article',)

    def get_success_url(self):
        """ Redirect to the instance's parent """
        return self.object.get_parent_url()


class ArticleDetailView(generic.DetailView):
    """ View for viewing an article's details """
    model = models.Article


class ArticleUpdateView(OptionalFormMixin, PermissionsMixin,
                        generic.edit.UpdateView):
    """ View for updating Article instances """
    fields = ('title', 'body', 'category', 'draft')
    form_class_setting = 'HELPCENTER_ARTICLE_UPDATE_FORM'
    model = models.Article
    permissions = ('helpcenter.change_article',)
    template_name_suffix = '_update'


class CategoryCreateView(OptionalFormMixin, PermissionsMixin,
                         generic.edit.CreateView):
    """View for creating new Category instances."""
    fields = ('title', 'parent')
    form_class_setting = 'HELPCENTER_CATEGORY_CREATE_FORM'
    model = models.Category
    permissions = ('helpcenter.add_category',)
    template_name_suffix = '_create'


class CategoryDeleteView(PermissionsMixin, generic.edit.DeleteView):
    """ View for deleting Category instances """
    model = models.Category
    permissions = ('helpcenter.delete_category',)

    def get_success_url(self):
        """ Return the url of the instances parent """
        return self.object.get_parent_url()


class CategoryDetailView(generic.DetailView):
    """ View for viewing a Category's details """
    model = models.Category

    def get_context_data(self, *args, **kwargs):
        """ Add custom context data """
        context = super(CategoryDetailView, self).get_context_data(
            *args, **kwargs)

        articles = self.object.article_list

        if not self.request.user.has_perm('helpcenter.change_article'):
            articles = articles.exclude(draft=True)

        context['articles'] = articles

        child_categories = models.Category.objects.filter(parent=self.object)
        context['categories'] = child_categories

        return context


class CategoryUpdateView(OptionalFormMixin, PermissionsMixin,
                         generic.edit.UpdateView):
    """ View for updating existing Category instances """
    fields = ('title', 'parent')
    form_class_setting = 'HELPCENTER_CATEGORY_UPDATE_FORM'
    model = models.Category
    permissions = ('helpcenter.change_category',)
    template_name_suffix = '_update'


class IndexView(generic.View):
    """ View for the helpcenter index (home page) """
    template_name = 'helpcenter/index.html'

    def get(self, request, *args, **kwargs):
        """ Handle get requests """
        return render(request, self.template_name, self.get_context_data())

    def get_context_data(self, *args, **kwargs):
        """ Get context data for a request """
        context = {}

        articles = models.Article.objects.filter(category=None)
        context['articles'] = articles

        categories = models.Category.objects.filter(parent=None)
        context['categories'] = categories

        return context


class SearchView(generic.View):
    """ View for searching article database """
    template_name = 'helpcenter/search.html'
    query_parameter = 'q'
    search_backend = SimpleSearch()

    def get(self, request, *args, **kwargs):
        """ Handle GET requests """
        self.request = request

        return render(request, self.template_name, self.get_context_data())

    def get_context_data(self, *args, **kwargs):
        """ Get context data for a request """
        context = {}

        query = self.request.GET.get(self.query_parameter, None)

        articles = self.get_search_results(query)
        context['articles'] = articles

        context['query'] = query

        return context

    def get_search_results(self, query):
        """ Return the results of a given query """
        if not query:
            return models.Article.objects.none()

        return self.search_backend.search(query)

helpcenter/templates/helpcenter/article_confirm_delete.html
{% extends 'helpcenter/base.html' %}


{% block page_title %}Delete Article{% endblock %}


{% block content %}

  <h1>Are You Sure?</h1>

  <p>Are you sure you want to delete the article "{{ object }}"?</p>

  <form method='post'>

    {% csrf_token %}

    <button type='submit'>Delete Article</button>

  </form>

  <a href='{{ object.get_absolute_url }}'>Back</a>

{% endblock %}

helpcenter/templates/helpcenter/article_create.html
{% extends 'helpcenter/base.html' %}


{% block page_title %}Create Article{% endblock %}


{% block content %}

  <h1>Create Article</h1>

  <form method='post'>

    {% csrf_token %}

    {{ form.as_p }}

    <button type='submit'>Create Article</button>

  </form>

{% endblock %}

helpcenter/templates/helpcenter/article_detail.html
{% extends 'helpcenter/base.html' %}

{% block page_title %}{{ article.title }}{% endblock %}

{% block content %}

  <h1>{{ article.title }}</h1>

  {% if perms.change_article %}
    <a href='{{ article.get_update_url }}'>Edit Article</a>
  {% endif %}

  {% if perms.delete_article %}
    <a href='{{ article.get_delete_url }}'>Delete Article</a>
  {% endif %}

  <div class='article-content'>
    {{ article.body|safe }}
  </div>

  <a href='{{ article.get_parent_url }}'>Back</a>

{% endblock %}

helpcenter/templates/helpcenter/article_update.html
{% extends 'helpcenter/base.html' %}


{% block page_title %}Update Article{% endblock %}


{% block content %}

  <h1>Update Article</h1>

  <form method='post'>

    {% csrf_token %}

    {{ form.as_p }}

    <button type='submit'>Update Article</button>

  </form>

{% endblock %}

helpcenter/templates/helpcenter/base.html
<!doctype html>
<html>

  <head>

    <title>{% block page_title %}Help Center{% endblock %}</title>

  </head>

  <body>

    {% block content %}{% endblock %}

  </body>

</html>

helpcenter/templates/helpcenter/category_confirm_delete.html
{% extends 'helpcenter/base.html' %}


{% block page_title %}Delete Category{% endblock %}


{% block content %}

  <h1>Are You Sure?</h1>

  <p>Are you sure you want to delete the category "{{ object }}"?</p>

  <form method='post'>

    {% csrf_token %}

    <button type='submit'>Delete Category</button>

  </form>

  <a href='{{ object.get_absolute_url }}'>Back</a>

{% endblock %}

helpcenter/templates/helpcenter/category_create.html
{% extends 'helpcenter/base.html' %}


{% block page_title %}Create Category{% endblock %}


{% block content %}

  <h1>Create Category</h1>

  <form method='post'>

    {% csrf_token %}

    {{ form.as_p }}

    <button type='submit'>Create Category</button>

  </form>

{% endblock %}

helpcenter/templates/helpcenter/category_detail.html
{% extends 'helpcenter/base.html' %}


{% block page_title %}{{ category.title }}{% endblock %}


{% block content %}

  <h1>{{ category.title }}</h1>

  {% if perms.change_category %}
    <a href='{{ category.get_update_url }}'>Edit Category</a>
  {% endif %}

  {% if perms.delete_category %}
    <a href='{{ category.get_delete_url }}'>Delete Category</a>
  {% endif %}

  {% if categories or perms.add_category %}

    <h2>Sub Categories</h2>

    {% include 'helpcenter/snippets/category_listing.html' %}

    {% if perms.add_category %}
      <a href='{% url "helpcenter:category-create" %}'>Create Category</a>
    {% endif %}

  {% endif %}

  {% if articles %}

    <h2>Articles</h2>

    {% include 'helpcenter/snippets/article_listing.html' %}

    {% if perms.add_article %}
      <a href='{% url "helpcenter:article-create" %}'>Create Article</a>
    {% endif %}

  {% endif %}

  <a href='{{ category.get_parent_url }}'>Back</a>

{% endblock %}

helpcenter/templates/helpcenter/category_update.html
{% extends 'helpcenter/base.html' %}


{% block page_title %}Update Category{% endblock %}


{% block content %}

  <h1>Update Category</h1>

  <form method='post'>

    {% csrf_token %}

    {{ form.as_p }}

    <button type='submit'>Update Category</button>

  </form>

{% endblock %}

helpcenter/templates/helpcenter/index.html
{% extends 'helpcenter/base.html' %}

{% block page_title %}Help Center{% endblock %}

{% block content %}

  <h1>Help Center</h1>

  <form id='search-form' action='{% url "helpcenter:search" %}' method='get'>
    <label for='search-input'>Search for Articles: </label>
    <input type='text' id='search-input' name='q' placeholder='Enter your search term' />

    <button type='submit'>Search</button>
  </form>

  {% if categories %}

    <h2>Categories</h2>

    {% include 'helpcenter/snippets/category_listing.html' %}

  {% endif %}

  {% if articles %}

    <h2>Articles</h2>

    {% include 'helpcenter/snippets/article_listing.html' %}

  {% endif %}

{% endblock %}

helpcenter/templates/helpcenter/search.html
{% extends 'helpcenter/base.html' %}

{% block page_title %}Search{% endblock %}

{% block content %}

  <h1>Search the Help Center</h1>

  <a href='{% url "helpcenter:index" %}'>Home</a>

  <form id='search-form' method='get'>

    <label for='search-input'>Search:</label><br />
    <input type='text' id='search-input' name='q' placeholder='Enter your search term' /><br />

    <button type='submit'>Search</button>

  </form>

  {% if query %}

    <div class='search-results'>

      <h3>Matches for '{{ query }}':</h3>

      {% if articles %}

        {% include 'helpcenter/snippets/article_listing.html' %}

      {% else %}

        <h4>There were no matches for your search</h4>

      {% endif %}

    </div>

  {% endif %}

{% endblock %}